ci(publish): refactor Docker image build and push process
- Switch from Docker to GitHub Container Registry (GHCR)
- Remove QEMU dependency
- Use `devcontainer` CLI for building images
- Implement semantic versioning of images

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,9 +1,17 @@
+# This workflow uses the `devcontainer` CLI to build the Docker image.
+# We chose the `devcontainer` CLI because we need integration with Dev Containers in Visual Studio Code.
+# As a result, we're not using Docker's `buildx` command for multi-architecture builds.
+# This workflow will only build the image for the host architecture (x86-64).
 name: Publish
 
 on:
   workflow_dispatch:
     inputs:
       imageName:
+        type: choice
+        options:
+          - 'archlinux'
+          # ... add more images here
         description: 'The name of the image to build and push'
         required: true
 
@@ -18,21 +26,61 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v4
 
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
+    - name: Install devcontainer CLI
+      run: npm install -g devcontainer-cli
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
-
-    - name: Login to Docker Hub
+    - name: Login to GitHub Container Registry
       uses: docker/login-action@v3
       with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v5
-      with:
-        context: src/${{ github.event.inputs.imageName }}/.devcontainer
-        push: true
-        tags: ${{ github.repository_owner }}/${{ github.event.inputs.imageName }}:latest
+    - name: Get latest version
+      id: latest-version
+      shell: bash
+      run: |
+        echo "🔍 Getting the latest version of the image from GitHub Container Registry..."
+        LATEST_VERSION=$(curl -s https://ghcr.io/v2/${{ github.repository_owner }}/${{ github.event.inputs.imageName }}/tags/list | jq -r '.tags[]' | sort -V | tail -n 1 || echo "0.0.0")
+        echo "✅ Latest version: $LATEST_VERSION"
+        echo "::set-output name=version::${LATEST_VERSION}"
+            
+    - name: Compare versions
+      id: compare-versions
+      shell: bash
+      run: |
+        echo "🔍 Comparing the new version with the latest version..."
+        VERSION=$(cat src/${{ github.event.inputs.imageName }}/VERSION)
+        LATEST_VERSION=${{ steps.latest-version.outputs.version }}
+        echo "🆕 New version: $VERSION"
+        echo "🔵 Latest version: $LATEST_VERSION"
+        if [[ $(printf '%s\n' "$VERSION" "$LATEST_VERSION" | sort -V | head -n 1) = "$LATEST_VERSION" ]]; then
+          echo "::set-output name=valid::false"
+          echo "❌ Error: The new version ($VERSION) is not larger than the current version ($LATEST_VERSION)."
+        else
+          echo "::set-output name=valid::true"
+          echo "::set-output name=version::${VERSION}"
+          echo "✅ The new version ($VERSION) is larger than the current version ($LATEST_VERSION). Proceeding with the build..."
+        fi
+      
+    - name: Build Docker image for x86-64 on ${{ github.event.inputs.imageName }}
+      if: steps.compare-versions.outputs.valid == 'true'
+      shell: bash
+      run: |
+        echo "🏗️ Building Docker image for x86-64 on ${{ github.event.inputs.imageName }}..."
+        cd src/${{ github.event.inputs.imageName }}/.devcontainer
+        # Build the image for the new version and the latest version
+        for tag in ${{ steps.compare-versions.outputs.version }} latest; do
+          devcontainer build --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageName }}:$tag
+          echo "✅ Docker image built successfully for tag $tag."
+        done
+      
+    - name: Push Docker image for x86-64 on ${{ github.event.inputs.imageName }}
+      shell: bash
+      run: |
+        echo "🚀 Pushing Docker image for x86-64 on ${{ github.event.inputs.imageName }}..."
+        # Push the image for the new version and the latest version
+        for tag in ${{ steps.compare-versions.outputs.version }} latest; do
+          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.imageName }}:$tag
+          echo "✅ Docker image pushed successfully for tag $tag."
+        done
